### ISSUE TITLE
导入到sonarqube后，插件提示安装成功，但无法搜索到p3c的规则

### ISSUE THREAD

**Issue by gzgccsu** [ccutzj/sonar-pmd-p3c#1]
导入到sonarqube后，插件提示安装成功，但无法搜索到p3c的规则
<img width="1339" alt="image" src="https://user-images.githubusercontent.com/12829204/206948199-d05f4d06-f02a-469f-9281-de62e7721cd5.png">
<img width="1314" alt="image" src="https://user-images.githubusercontent.com/12829204/206949635-8e1b7eb9-1789-4839-9d99-c7a54b1e256c.png">

**Comment by ccutzj** [comment]
![image](https://user-images.githubusercontent.com/50936314/209597521-86be8063-24f9-4856-b4bf-40839711ca83.png)
语言选择->java
仓库选择->PMD
应该就可以查看到，如果还是没有可以搜索“编码规范”关键字

**Comment by ccutzj** [comment]
> 语言选择->java
> 仓库选择->PMD
> 应该就可以查看到，如果还是没有可以搜索“编码规范”关键字
